export const ProjectList = [
  {
    id: 2,
    pinned: true,
    title: "Kartcaw",
    subtitle: "Gokart analysis tracker",
    description:
      "Visualize telemetry data, cornering techniques phases enable to evaluate performance.",
    paragraph: "The client’s needs are to analyze and evaluate their Gokart race performance using telemetric data such as velocity, timestamps, braking zones, entry/exit points. This project will create a session of race and track the user using build-in gps. After the session, data will appear as telemetric data that helps user to evaluate their performance.",
      techStack: ["SwiftUI", "UIKit", "MapKit", "CoreData"],
    role: "half Coder & Designer",
    responsibilties: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Coding",
    ],
    thumbnail: "/img/project/asset/Kartcaw-asset.png",
    toneColor: "E9F0F8",
    images: [
      "/img/project/c2/CreateSessionEnds.png",
      "/img/project/c2/CreateSessionStart.png",
      "/img/project/c2/CreateTrack.png",
      "/img/project/c2/DetailSummaryLapComparison.png",
      "/img/project/c2/HomePage.png",
    ],
    link: "https://netflix.com",
  },
  {
    id: 3,
    pinned: true,
    title: "Eudori",
    subtitle: "Electric circuit gamification",
    description:
      "Help first and second year electronics engineer to learn electric circuit by visualization.",
      paragraph: "The user’s needs are to understand electrical circuit components especially in capacitors problem with attractive way. This project using gamification method to attract user to easily understand with attractive way. The Project includes story about a character who has to fix an electrical circuit in order to earn money. there has 3 options of problem, reverse polarity, high temperature, wrong capacitors value.",
    techStack: ["SwiftUI", "ARKit", "RealityKit", "VisionKit", "UIKit"],
    role: "Coder",
    responsibilties: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Coding",
    ],
    thumbnail: "/img/project/asset/Eudori-asset.png",
    toneColor: "FFFAED",
    images: [
      "/img/project/c3/CircuitStory.png",
      "/img/project/c3/NewItemFeature.png",
      "/img/project/c3/Onboarding.png",
      "/img/project/c3/ThermalView.png",
      "/img/project/c3/TutorialView.png",
    ],
    link: "https://google.com",
  },
  {
    id: 4,
    pinned: false,
    title: "Finia",
    subtitle: "Money manager with monetization and AI powered",
    description:
      "A money manager app to input and analyze expenses and incomes with financial helper using AI Companion. This project aims to focus to learn monetization and value proposition.",
      paragraph: "The project is to manage such as input expenses and incomes and analyze with filters by date and using model AI Companion. This AI Companion will help users to analyze, plan, and giving advice for users finance. Money managers have great potential considering that this app is a red ocean. Compare existing competitors and look for opportunities to create a value proposition. ",
    techStack: ["SwiftUI", "CoreData", "OpenAI API", "RevenueCat", "AdMob"],
    role: "half Coder & Designer",
    responsibilties: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Coding",
    ],
    thumbnail: "/img/project/asset/finia-asset.png",
    toneColor: "F9F7FF",
    images: [
      "/img/project/c5/AIAssistantView.png",
      "/img/project/c5/ExpensesFilter.png",
      "/img/project/c5/HomeView.png",
      "/img/project/c5/SettingsView.png",
      "/img/project/c5/SubscribeView.png",
    ],
    link: "https://meta.com",
  },
  {
    id: 5,
    pinned: false,
    title: "Vocality",
    subtitle: "Speak practice app with AI powered",
    description:
      "Help third culture kids who returning to Indonesia to enchance their clarity according to cross-cultural understanding in Indonesia. ",
    paragraph: "The user’s needs are to giving a place for practice Bahasa Indonesia based on Cross-Cultural Understanding. The practice has a question that user need to answer whether  speaking freely and with a teleprompter. This practice has a summary about user score and if there are filler words, and/or repeated words that affect the score itself. ",
    techStack: ["SwiftUI", "CoreData", "CoreML", "AVFoundation", "Gemini API"],
    role: "Coder & half Designer",
    responsibilties: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Coding",
    ],
    thumbnail: "/img/project/asset/vocality-asset.png",
    toneColor: "FFF8F1",
    images: [
      "/img/project/c6/HomeView.png",
      "/img/project/c6/AnalyticalView.png",
      "/img/project/c6/History.png",
      "/img/project/c6/PracticeSummary.png",
      "/img/project/c6/QuestionView.png",
      "/img/project/c6/ScriptedAnswer.png",
      "/img/project/c6/UnscriptedAnswer.png",
    ],
    link: "https://amazon.com",
  },
  {
    id: 6,
    pinned: true,
    title: "Jörd",
    subtitle: "Light exercise reminder",
    description:
      "Help desk-based freelancers who work from home by doing light exercise, thereby increasing their daily energy.",
    paragraph: "A macOS-based application designed to assist desk-based freelancers working from home, who have dense and unpredictable work schedules, by utilizing pocket time for light exercise to boost daily energy, maintain focus, and sustain work productivity. The application provides customizable exercise reminders, allowing users to set preferred intervals and types of light exercises, ensuring flexibility to accommodate their busy routines.",
    techStack: ["SwiftUI", "SwiftData"],
    role: "PM & Coder",
    responsibilties: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Coding",
    ],
    thumbnail: "/img/project/asset/Jord-asset.png",
    toneColor: "E0E4EC",
    images: [
      "/img/project/c7/jord-1.png",
      "/img/project/c7/jord-2.png",
      "/img/project/c7/jord-3.png",
      "/img/project/c7/jord-4.png",
    ],
    link: "https://amazon.com",
  },
];
