export const ProjectList = [
    {
        id: 2,
        pinned: true,
        title: "Kartcaw",
        subtitle: "Gokart analysis tracker",
        description:
            "Visualize telemetry data, cornering techniques phases enable to evaluate performance.",
                    techStack: ["SwiftUI", "UIKit", "MapKit", "CoreData"],
        role: "half Coder & Designer",
        responsibilties: [
            "User Research",
            "Wireframing",
            "Prototyping",
            "Visual Design",
            "Coding",
        ],
        thumbnail: "/img/project/asset/Kartcaw-asset.png",
        toneColor: "E9F0F8",
        images: ["/img/project/c2/CreateSessionEnds.png", "/img/project/c2/CreateSessionStart.png", "/img/project/c2/CreateTrack.png", "/img/project/c2/DetailSummaryLapComparison.png", "/img/project/c2/HomePage.png"],
        link: "https://netflix.com",
    },
    {
        id: 3,
        pinned: true,
        title: "Eudori",
        subtitle: "Electric circuit gamification",
        description:
            "Help first and second year electronics engineer to learn electric circuit by visualization.",
                    techStack: ["SwiftUI", "ARKit", "RealityKit", "VisionKit", "UIKit"],
        role: "Coder",
                responsibilties: [
            "User Research",
            "Wireframing",
            "Prototyping",
            "Visual Design",
            "Coding",
        ],
        thumbnail: "/img/project/asset/Eudori-asset.png",
        toneColor: "FFFAED",
        images: ["/img/project/c3/CircuitStory.png", "/img/project/c3/NewItemFeature.png", "/img/project/c3/Onboarding.png", "/img/project/c3/ThermalView.png", "/img/project/c3/TutorialView.png"],
        link: "https://google.com",
    },
    {
        id: 4,
        pinned: false,
        title: "Finia",
        subtitle: "Money manager with monetization and AI powered",
        description:
            "A money manager app to input and analyze expenses and incomes with financial helper using AI Companion. This project aims to focus to learn monetization and value proposition.",
                    techStack: ["SwiftUI", "CoreData", "OpenAI API", "RevenueCat", "AdMob"],
        role: "half Coder & Designer",
                responsibilties: [
            "User Research",
            "Wireframing",
            "Prototyping",
            "Visual Design",
            "Coding",
        ],
        thumbnail: "/img/project/asset/finia-asset.png",
        toneColor: "FFF8F1",
        images: ["/img/project/c5/AIAssistantView.png", "/img/project/c5/ExpensesFilter.png", "/img/project/c5/HomeView.png", "/img/project/c5/SettingsView.png", "/img/project/c5/SubscribeView.png"],
        link: "https://meta.com",
    },
    {
        id: 5,
        pinned: false,
        title: "Vocality",
        subtitle: "Speak practice app with AI powered",
        description:
            "Help third culture kids who returning to Indonesia to enchance their clarity according to cross-cultural understanding in Indonesia. e kids who returning to Indonesia to enchance their clarity according to cross-cultural understanding in Indonesia.",
                    techStack: ["SwiftUI", "CoreData", "CoreML", "AVFoundation", "Gemini API"],
        role: "Coder & half Designer",
                responsibilties: [
            "User Research",
            "Wireframing",
            "Prototyping",
            "Visual Design",
            "Coding",
        ],
        thumbnail: "/img/project/asset/vocality-asset.png",
        toneColor: "F9F7FF",
        images: ["/img/project/c6/HomeView.png", "/img/project/c6/AnalyticalView.png", "/img/project/c6/History.png", "/img/project/c6/PracticeSummary.png", "/img/project/c6/QuestionView.png", "/img/project/c6/ScriptedAnswer.png", "/img/project/c6/UnscriptedAnswer.png"],
        link: "https://amazon.com",
    },
     {
        id: 6,
        pinned: true,
        title: "Jörd",
        subtitle: "Light exercise reminder",
        description:
            "A macOS-based application that helps desk-based freelancers who work from home, have busy and unpredictable working hours, by utilizing their spare time (pocket time) to do light exercise, thereby increasing their daily energy, allowing them to stay focused and maintain their work productivity.",
                    techStack: ["SwiftUI", "SwiftData"],
        role: "PM & Coder",
        responsibilties: [
            "User Research",
            "Wireframing",
            "Prototyping",
            "Visual Design",
            "Coding",
        ],
        thumbnail: "/img/project/asset/Jord-asset.png",
        toneColor: "F1F1F1",
        images: ["/img/project/c6/HomeView.png", "/img/project/c6/AnalyticalView.png", "/img/project/c6/History.png", "/img/project/c6/PracticeSummary.png", "/img/project/c6/QuestionView.png", "/img/project/c6/ScriptedAnswer.png", "/img/project/c6/UnscriptedAnswer.png"],
        link: "https://amazon.com",
    }
];