"use client"
import Head from "next/head";
import styles from '../styles/effect.module.css';
import { useEffect } from "react";

const sosmed = {
  instagram: {
      name: 'instagram',
      icon: '/icons/instagram.png',
      link: 'https://www.instagram.com/ariqtb',
      styles: 'bg-pink-500 hover:bg-pink-300 text-white hover:text-pink-600',
      tag: '#ig'
  },
  facebook: {
      name:'facebook',
      icon: '/icons/facebook.png',
      link: 'https://www.facebook.com/ariq.naufal.395',
      styles: 'bg-blue-600 hover:bg-blue-300 text-white hover:text-blue-600',
      tag: '#fb'
  },
  linkedin: {
      name: 'linkedin',
      icon: '/icons/linkedin.png',
      link: 'https://www.linkedin.com/in/tubagus-ariq/',
      styles: 'bg-blue-100 hover:bg-blue-200 text-blue-500 hover:text-white',
      tag: '#li'
  },}

type SocialButtonProps = {
  platform: keyof typeof sosmed;
};

const SocialButton: React.FC<SocialButtonProps> = ({ platform }) => {
  const { name, link, icon, styles } = sosmed[platform];

  return (
    <a
      href={link}
      target="_blank"
      rel="noopener noreferrer"
      className={`flex items-center text-white font-bold py-2 px-4 rounded ${styles}`}
    >
      <img src={icon} alt={`${name} icon`} className="w-5 h-5 mr-2"/>
      {name}
      {/* <span className="mr-2">{icon}</span> */}
    </a>
  );
};

const Banner: React.FC = () => {
  useEffect(() => {
    const photoElement = document.querySelector(`.${styles.component}`);
    if(photoElement){
      photoElement.classList.add(styles['fade-in']);
    }
  }, []);

  return(
    <div className="flex flex-col items-center justify-center min-h-screen py-2">

      <main className={`flex flex-col items-center justify-center w-full flex-1 px-20 text-center ${styles.component}`}>
        <h1 className="text-4xl font-bold">
          Find me on <a className="text-pink-600">Social </a><a className="text-blue-600" href="#">Media!</a>
        </h1>

        <div className="flex mt-3 space-x-4 items-center">
          <SocialButton platform="facebook" />
          <SocialButton platform="instagram" />
          <SocialButton platform="linkedin" />
        </div>
      </main>
    </div>
  )
}
export default Banner;

// export default function Bannerr() {
//   return <></>;
// }

// <div>
//   <Head>
//     <title>My Social Media App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>

//   <main style={{ padding: "20px" }}>
//     <h1>Welcome to My Social Media App</h1>
//     <TwitterButton url={url} text={text} />
//   </main>
// </div>
